### PR TITLE
Fix metadata aggregator

### LINKED ISSUE #652: [BUG]: aggregator_metadata_group may be having oversize packing operation
**Describe the bug**
aggregator_metadata_group may be having oversize packing operation
For an Example:
1. Set maxEventsLength is 30
2. The input events size is 3000
3. The expected behavior is the input events would be split into 100 packets. But now there's only one packet.

### PR DESCRIPTION
**Pull request by EvanLjp**
https://github.com/alibaba/ilogtail/issues/652

### CODE REVIEW

File: plugins/aggregator/metadatagroup/aggregator_metadata_group.go [hunk 1]
```diff
@@ -31,44 +32,130 @@ const (
...
 
-	nowEventsLength     int
-	nowEventsByteLength int
-	maxEventsLength     int
-	maxEventsByteLength int
+	nowEventsLength      int
+	nowEventsByteLength  int
+	maxEventsLength      int
+	maxEventsByteLength  int
+	oversizeDirectOutput bool
```
Comment (yyuuttaaoo) [inline plugins/aggregator/metadatagroup/aggregator_metadata_group.go:43]: 反一反，叫dropOversizedEvent是不是好理解一些

**Review by yyuuttaaoo — CHANGES_REQUESTED** [review]

**Review by yyuuttaaoo — APPROVED** [review]

**Review by snakorse — APPROVED** [review]
LGTM
